version: '3'

services:
  first-go:
    image: first-go
    command: npm start
    build: .
    volumes:
      - .:/usr/src/app
    # environment:
    #   NODE_ENV: production
    ports:
      - 3000:3000